### ISSUE TITLE
How to check whether snapd package is installed?

### ISSUE THREAD

**Issue by whiskeyPeak** [canonical/snapd.dart#77]
In the current implementation of the flutter snap store, if snapd is not installed a socketException will be thrown during startup because a connection to the snapd server cannot be facilitated.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: Connection refused, errno = 111), address = /var/run/snapd.socket, port = 0
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:682:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1827:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      Socket._startConnect (dart:io-patch/socket_patch.dart:2048:22)
#4      Socket.startConnect (dart:io/socket.dart:759:21)
#5      new SnapdClient.<anonymous closure> (package:snapd/src/snapd_client.dart:1000:21)
#6      _ConnectionTarget.connect (dart:_http/http_impl.dart:2443:28)
#7      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2867:12)
#8      _HttpClient._getConnection (dart:_http/http_impl.dart:2872:12)
#9      _HttpClient._openUrl (dart:_http/http_impl.dart:2727:12)
#10     _HttpClient.getUrl (dart:_http/http_impl.dart:2596:48)
#11     SnapdClient._getSync (package:snapd/src/snapd_client.dart:1284:23)
#12     SnapdClient.find (package:snapd/src/snapd_client.dart:1147:24)
#13     SnapService.findSnapsBySection (package:software/services/snap_service.dart:142:34)
#14     SnapService._loadSection (package:software/services/snap_service.dart:284:30)
#15     SnapService.init.<anonymous closure> (package:software/services/snap_service.dart:84:19)
<asynchronous suspension>
```

https://github.com/ubuntu-flutter-community/software/pull/659 tried to fix this by catching the exception, but because the exception thrown is not precise enough, there may be scenarios where a SocketException is thrown even when snapd is installed.

@robert-ancell What do you think about the solution in https://github.com/ubuntu-flutter-community/software/pull/659#issuecomment-1368082283, simply running a bash command and checking whether the snapd package is installed this way? 
We could also throw additional more precise exceptions directly in the snapd.dart package.

**Comment by whiskeyPeak** [comment]
Closing because this is needed.
